title: Matthieu Rémy
email: remy.matthieu@gmail.com
description: >-
  Adventures in open-source software.
baseurl: ""
url: "http://matthieure.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: remyMatthieu
github_username:  remyma
linkedin_username: matthieu-remy-6794355

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

date_format: "%F"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

livereload: true
