title: Matthieu Rémy
email: remy.matthieu@gmail.com
description: >-
  Tech blog about service architecture, devops, and opensource.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: remyMatthieu
github_username:  remyma
linkedin_username: matthieu-remy-6794355

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

date_format: "%F"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
